import { and, desc, eq } from "drizzle-orm";
import { consents, healthSubjects, uploads } from "../../../db/schema";
import { apiIdentity, audit, db, files, id, json, unauthorized } from "../_lib";

export async function GET(request:Request){const identity=await apiIdentity(request);if(!identity)return unauthorized();return Response.json({uploads:await db().select().from(uploads).where(eq(uploads.ownerUserId,identity.userId)).orderBy(desc(uploads.createdAt)).limit(50)});}
export async function POST(request:Request){
  const identity=await apiIdentity(request);if(!identity)return unauthorized();const form=await request.formData();const file=form.get("file"),subjectId=String(form.get("subjectId")||"");if(!(file instanceof File))return Response.json({error:"file_required"},{status:400});if(file.size>10*1024*1024)return Response.json({error:"file_too_large","limitMb":10},{status:413});if(!file.type.startsWith("image/")&&file.type!=="application/pdf")return Response.json({error:"unsupported_type"},{status:415});
  const database=db();const subject=(await database.select().from(healthSubjects).where(and(eq(healthSubjects.id,subjectId),eq(healthSubjects.ownerUserId,identity.userId))).limit(1))[0];if(!subject)return Response.json({error:"invalid_subject"},{status:403});const permission=(await database.select().from(consents).where(and(eq(consents.ownerUserId,identity.userId),eq(consents.subjectId,subjectId),eq(consents.scope,"media_processing"),eq(consents.status,"granted"))).limit(1))[0];if(!permission)return Response.json({error:"consent_required",scope:"media_processing"},{status:403});
  const uploadId=id("upload"),objectKey=`${identity.userId}/${subjectId}/${uploadId}/${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;await files().put(objectKey,file.stream(),{httpMetadata:{contentType:file.type},customMetadata:{ownerUserId:identity.userId,subjectId,originalName:file.name}});await database.insert(uploads).values({id:uploadId,ownerUserId:identity.userId,subjectId,objectKey,fileName:file.name,contentType:file.type,size:file.size,status:"awaiting_quality_check",qualityJson:json({status:"pending",reason:"quality_and_ocr_provider_not_configured"})});await audit(identity.userId,"image_uploaded","upload",uploadId,subjectId,{contentType:file.type,size:file.size,status:"awaiting_quality_check"});return Response.json({id:uploadId,status:"awaiting_quality_check",processingAvailable:false},{status:201});
}
