"use client";

import { useEffect, useRef, useState } from "react";

const nav = [["＋","新对话","健康问答"],["▤","图片解读","图片解读"],["▣","健康档案","健康档案"],["◎","目标与提醒","目标与提醒"],["⌁","设备数据","设备数据"],["✚","医疗服务","医疗服务"]];
const members = ["我"];
const action = async (payload:Record<string,unknown>) => {
  const response=await fetch("/api/product",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});
  const data=await response.json();if(!response.ok)throw new Error(data.error||"request_failed");return data;
};

export default function Home(){
  const [page,setPage]=useState("健康问答");
  const [sideCollapsed,setSideCollapsed]=useState(false);
  const [member,setMember]=useState("我");
  const [notice,setNotice]=useState("");
  const [privacy,setPrivacy]=useState(false);
  const [history,setHistory]=useState(false);
  const [bootstrap,setBootstrap]=useState<any>(null);
  const [conversation,setConversation]=useState<any>(null);
  const [conversationId,setConversationId]=useState("");
  const load=async()=>{try{const response=await fetch("/api/bootstrap");if(response.ok){const data=await response.json();setBootstrap(data);if(data.subjects?.[0])setMember(data.subjects[0].name)}}catch{}};
  useEffect(()=>{load();const stored=localStorage.getItem("abao-sidebar-collapsed");setSideCollapsed(stored===null?window.innerWidth<760:stored==="true")},[]);
  const subjectId=bootstrap?.subjects?.find((s:any)=>s.name===member)?.id??(member==="我"?bootstrap?.subjects?.[0]?.id:"")??"";
  const go=(next:string)=>{setPage(next);setNotice("");window.scrollTo({top:0,behavior:"smooth"})};
  const toggleSide=()=>setSideCollapsed(value=>{const next=!value;localStorage.setItem("abao-sidebar-collapsed",String(next));return next});
  const newConversation=()=>{setConversation(null);setConversationId("");go("健康问答")};
  const openConversation=async(id:string)=>{try{const response=await fetch(`/api/product?resource=messages&conversationId=${encodeURIComponent(id)}`);const data=await response.json();if(!response.ok)throw new Error();setConversationId(id);setConversation({items:data.messages});setHistory(false);go("健康问答")}catch{setNotice("历史对话暂时无法读取")}};
  const begin=async(text:string)=>{try{if(!subjectId)throw new Error("profile_unavailable");const latestAiConsent=[...(bootstrap?.consents??[])].reverse().find((c:any)=>c.subjectId===subjectId&&c.scope==="external_ai_processing");if(latestAiConsent?.status!=="granted"){const confirmed=window.confirm("为生成智能回答，大象阿宝会把本轮输入和必要的最近对话发送给 DeepSeek API 处理。请勿输入与健康问题无关的身份信息。你可以随时在隐私设置中撤回授权。是否同意？");if(!confirmed){setNotice("未授权第三方 AI 处理，本次不会发送健康内容");return}await action({action:"set_consent",subjectId,scope:"external_ai_processing",purpose:"将必要的健康对话发送给 DeepSeek API 生成回答",status:"granted"});await load()}const created=await action({action:"create_conversation",subjectId,title:text.slice(0,30)});const result=await action({action:"send_message",conversationId:created.id,content:text,inputType:"text"});setConversationId(created.id);setConversation(result);await load()}catch{setConversation({userMessage:{role:"user",content:text},assistantMessage:{role:"assistant",content:"为了更准确地理解，我还想确认：这种情况持续多久、严重程度有没有变化？",riskLevel:"general_consultation",modelVersion:"local-fallback"}})}go("健康问答")};
  return <main className={`shell app-shell ${sideCollapsed?"side-collapsed":""}`}>
    <aside className="side">
      <div className="side-head"><button className="brand" onClick={newConversation} title="大象阿宝"><span className="brand-elephant">🐘</span><span className="brand-name">大象阿宝<small>AI 健康朋友</small></span></button><button className="side-toggle" onClick={toggleSide} aria-label={sideCollapsed?"展开侧栏":"收起侧栏"} title={sideCollapsed?"展开侧栏":"收起侧栏"}>{sideCollapsed?"›":"‹"}</button></div>
      <nav aria-label="产品功能">{nav.map(([icon,label,target])=><button key={label} title={label} className={page===target?"active":""} onClick={()=>target==="健康问答"?newConversation():go(target)}><i>{icon}</i><span>{label}</span></button>)}</nav>
      <div className="side-foot"><button onClick={()=>setHistory(true)}><i>⌕</i><span>历史与检索</span></button><button onClick={()=>setPrivacy(true)}><i>◇</i><span>隐私与授权</span></button></div>
    </aside>
    <section className="main">
      <header className="top chatgpt-top"><button className="mobile-side-toggle" onClick={toggleSide} aria-label="切换侧栏">☰</button><button className="model-title" onClick={newConversation}>大象阿宝 <span>健康助手</span></button><div className="top-actions"><button className="subject-switch" onClick={()=>{const names=(bootstrap?.subjects??[]).filter((s:any)=>s.authorizationStatus==="active").map((s:any)=>s.name);if(names.length>1)setMember(names[(names.indexOf(member)+1)%names.length]);else setNotice("请先在健康档案中创建并授权家庭成员")}}>为 {member} 咨询⌄</button><button className="top-icon" onClick={()=>setHistory(true)} aria-label="搜索历史">⌕</button><button className="user" onClick={()=>setPrivacy(true)} aria-label="隐私与账号">我</button></div></header>
      <div className={`content ${page==="健康问答"?"chat-content":""}`}><Panel page={page} go={go} member={member} setMember={setMember} setNotice={setNotice} subjectId={subjectId} bootstrap={bootstrap} conversation={conversation} conversationId={conversationId} reload={load} onStart={begin}/></div>
    </section>
    {notice&&<div className="toast" role="status">{notice}<button onClick={()=>setNotice("")}>×</button></div>}
    {privacy&&<PrivacyModal close={()=>setPrivacy(false)} setNotice={setNotice} subjectId={subjectId} reload={load}/>} 
    {history&&<HistoryModal close={()=>setHistory(false)} go={go} openConversation={openConversation} subjectId={subjectId}/>} 
  </main>
}

function AgentHome({member,setMember,subjects,go,onStart,openConversation,subjectId,reload,setPrivacy,setHistory,notice,setNotice,privacy,history}:any){
  const [text,setText]=useState("");
  const start=()=>{if(!text.trim())return;onStart(text.trim())};
  return <main className="agent-home">
    <header className="agent-top"><button className="agent-brand" aria-label="大象阿宝首页"><span>🐘</span><b>大象阿宝</b></button><div className="agent-actions"><button onClick={()=>setHistory(true)}>⌕　历史记录</button><button onClick={()=>{const names=(subjects??[]).filter((s:any)=>s.authorizationStatus==="active").map((s:any)=>s.name);if(names.length>1)setMember(names[(names.indexOf(member)+1)%names.length]);else setNotice("请先在健康档案中创建并完成家庭成员授权")}}>为 {member} 咨询⌄</button><button className="agent-avatar" onClick={()=>setPrivacy(true)}>我</button></div></header>
    <section className="agent-stage"><div className="agent-welcome"><div className="agent-mark">🐘</div><h1>你好，我是阿宝</h1><p>你的 AI 健康朋友。今天想聊些什么？</p></div><div className="agent-composer"><textarea value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();start()}}} placeholder="描述健康问题、症状，或上传健康资料" aria-label="向阿宝提问"/><div className="agent-tools"><div><button onClick={()=>setNotice("图片上传会在使用时请求相册或相机授权")} title="上传图片">＋</button><button onClick={()=>setNotice("语音输入会在使用时请求麦克风授权")} title="语音输入">♩</button></div><button className="agent-send" onClick={start} aria-label="发送">↑</button></div></div><div className="agent-prompts"><span>你可以试试</span>{["最近总是睡不好","帮我看懂体检报告","如何建立健康目标"].map(x=><button key={x} onClick={()=>setText(x)}>{x}</button>)}</div><p className="agent-disclaimer">内容仅供健康信息参考，不能替代专业医生的诊断和治疗建议。如有紧急症状，请立即联系急救或前往急诊。</p></section>
    <button className="agent-manage" onClick={()=>go("健康档案")}>健康管理　›</button>
    {notice&&<div className="toast" role="status">{notice}<button onClick={()=>setNotice("")}>×</button></div>}
    {privacy&&<PrivacyModal close={()=>setPrivacy(false)} setNotice={setNotice} subjectId={subjectId} reload={reload}/>} 
    {history&&<HistoryModal close={()=>setHistory(false)} go={go} openConversation={openConversation} subjectId={subjectId}/>} 
  </main>
}

function Panel(props:any){switch(props.page){
  case "健康问答": return <AskPage {...props}/>;
  case "图片解读": return <ReportPage {...props}/>;
  case "健康档案": return <ArchivePage {...props}/>;
  case "目标与提醒": return <GoalPage {...props}/>;
  case "设备数据": return <DevicePage {...props}/>;
  case "医疗服务": return <ServicePage {...props}/>;
  default:return <HomePage {...props}/>;
}}

function HomePage({go,member,setMember,setNotice,bootstrap}:any){return <>
  <section className="hero"><div className="hero-copy"><span className="eyebrow">AI 健康朋友</span><h1>从一个健康问题开始，<br/>持续照顾你和家人</h1><p>用文字、语音或图片描述问题。阿宝会补充询问必要信息，并在需要时连接专业医疗服务。</p><div className="hero-actions"><button className="primary" onClick={()=>go("健康问答")}>开始健康问答</button><button onClick={()=>go("图片解读")}>上传健康资料</button></div><small>AI 输出仅供参考，不能替代专业医生的诊断和治疗建议。</small></div><div className="hero-art" aria-hidden="true"><span className="tag t1">主动追问</span><span className="tag t2">风险分流</span><div>🐘</div><span className="tag t3">档案参考</span></div></section>
  <SubjectBar member={member} setMember={setMember} subjects={bootstrap?.subjects}/>
  <section className="section"><div className="section-title"><div><span>核心能力</span><h2>围绕健康管理的完整闭环</h2></div><p>问题理解、行动建议、持续记录与专业服务连接</p></div><div className="feature-grid">{[["◌","健康问答","文字、语音、图片提问与主动追问","健康问答"],["▤","图片与文件解读","质量检查、字段确认、通俗解释","图片解读"],["▣","个人与家庭档案","按人、时间和资料类型管理记录","健康档案"],["◎","目标、计划与提醒","可编辑计划、打卡与提醒控制","目标与提醒"],["⌁","设备数据接入","同步状态、数据来源与质量说明","设备数据"],["✚","医疗服务连接","在线问诊、预约挂号与云陪诊","医疗服务"]].map(([icon,title,desc,target])=><button key={title} onClick={()=>go(target)}><i>{icon}</i><span><b>{title}</b><em>{desc}</em></span><strong>›</strong></button>)}</div></section>
  <section className="safety"><i>!</i><div><b>医疗安全是所有功能的前提</b><span>疑似急症时停止普通问答，明确建议联系急救或立即线下就医；信息不足时不会输出确定性结论。</span></div><button onClick={()=>setNotice("安全边界：急症优先、说明不确定性、高风险操作需用户确认")}>查看安全边界</button></section>
</>}

function SubjectBar({member,setMember,subjects}:any){const names=subjects?.length?subjects.filter((s:any)=>s.authorizationStatus==="active").map((s:any)=>s.name):members;return <div className="subject-bar"><span>为谁管理健康</span>{names.map((m:string)=><button key={m} className={member===m?"selected":""} onClick={()=>setMember(m)}>{m}</button>)}<p>只有已授权主体可被使用；不同成员的数据不会混入同一上下文。</p></div>}

function PageIntro({kicker,title,desc,icon}:any){return <div className="page-intro"><span>{kicker}</span><h1>{title}</h1><p>{desc}</p><i>{icon}</i></div>}

function AskPage({member,setNotice,conversation,conversationId,onStart}:any){
  const [text,setText]=useState("");const [items,setItems]=useState<any[]>([]);const [sending,setSending]=useState(false);
  useEffect(()=>{if(conversation)setItems(conversation.items??[conversation.userMessage,conversation.assistantMessage].filter(Boolean))},[conversation]);
  const submit=async(value?:string)=>{const content=(value??text).trim();if(!content||sending)return;setSending(true);setText("");try{if(conversationId){const result=await action({action:"send_message",conversationId,content,inputType:"text"});setItems(v=>[...v,result.userMessage,result.assistantMessage])}else await onStart(content)}catch{setNotice("会话暂时不可用，请稍后重试")}finally{setSending(false)}};
  const rate=async(messageId:string,type:string)=>{try{if(messageId)await action({action:"feedback",messageId,type});setNotice("感谢反馈，已用于质量与安全改进")}catch{setNotice("反馈暂未保存")}};
  return <div className="chat-page"><div className="chat-scroll">
    {!items.length&&<section className="chat-welcome"><div className="welcome-mark">🐘</div><h1>你好，我是阿宝</h1><p>你的 AI 健康朋友。今天想聊些什么？</p><div className="starter-grid">{[["最近总是睡不好","一起梳理睡眠时间与影响因素"],["帮我看懂体检报告","上传资料前会先征求授权"],["最近经常感到头痛","先了解持续时间与伴随症状"],["想建立健康目标","从睡眠、运动或饮食开始"]].map(([title,desc])=><button key={title} onClick={()=>submit(title)}><b>{title}</b><span>{desc}</span></button>)}</div></section>}
    {!!items.length&&<div className="conversation">{items.map((m:any,i:number)=>m.role==="user"?<div className="mine" key={m.id||i}>{m.content}</div>:m.riskLevel==="emergency"?<div className="risk-card" key={m.id||i}><i>!</i><h2>需要立即处理的高风险情况</h2><p>{m.content}</p><button onClick={()=>setNotice("请立即联系当地急救服务或前往急诊")}>紧急行动建议</button></div>:<div className="abo" key={m.id||i}><span>🐘</span><div><b>{m.riskLevel==="high_risk"?"需要更谨慎评估":"还需要补充信息"}</b><p>{m.content}</p><div className="choice-row"><button onClick={()=>setText("少于 1 周")}>少于 1 周</button><button onClick={()=>setText("1–4 周")}>1–4 周</button><button onClick={()=>setText("超过 1 个月")}>超过 1 个月</button></div><small>上下文：{member}的当前对话 · {m.modelVersion||"规则降级模式"} · 暂无外部医学来源</small>{m.id&&<div className="feedback-row"><button onClick={()=>rate(m.id,"helpful")}>有帮助</button><button onClick={()=>rate(m.id,"not_helpful")}>无帮助</button><button onClick={()=>rate(m.id,"safety_issue")}>安全问题</button><button onClick={()=>rate(m.id,"factual_error")}>事实错误</button></div>}</div></div>)}</div>}
  </div><div className="chat-dock"><div className="composer unified-composer"><textarea value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();submit()}}} placeholder="描述健康问题、症状，或上传健康资料" aria-label="向阿宝提问"/><div><button onClick={()=>setNotice("图片上传前会请求相册或文件授权")}>＋</button><button onClick={()=>setNotice("语音输入需要麦克风授权和语音服务配置")}>♩</button><span className="composer-spacer"/><button className="send-round" onClick={()=>submit()} disabled={sending||!text.trim()} aria-label="发送">{sending?"…":"↑"}</button></div></div><p className="boundary">内容仅供健康信息参考，不能替代专业医生诊断；紧急情况请立即联系急救或前往急诊。</p></div></div>
}

function ReportPage({setNotice,subjectId}:any){const input=useRef<HTMLInputElement>(null);const [fileName,setFileName]=useState("");const [status,setStatus]=useState("等待上传");const upload=async(file:File)=>{if(!subjectId){setNotice("请先完成健康主体初始化");return}setFileName(file.name);setStatus("请求处理授权");try{await action({action:"set_consent",subjectId,scope:"media_processing",purpose:"对健康资料进行质量检查、字段提取与解释",status:"granted"});const form=new FormData();form.append("file",file);form.append("subjectId",subjectId);setStatus("安全上传中");const response=await fetch("/api/uploads",{method:"POST",body:form});const data=await response.json();if(!response.ok)throw new Error(data.error);setStatus(data.processingAvailable?"正在检查质量":"已保存，等待质量检测服务");setNotice("资料已加密保存；尚未接入 OCR，不会生成未经验证的解读")}catch{setStatus("上传失败，可重试");setNotice("资料未能保存，请检查授权或稍后重试")}};return <div className="page"><PageIntro kicker="图片与文件解读" title="先确认原始信息，再理解健康资料" desc="适用于检查报告、病例、处方和药盒。识别字段经你确认后才会生成解释。" icon="▤"/><section className="upload-card"><button className="upload" onClick={()=>input.current?.click()}><i>{fileName?"✓":"＋"}</i><b>{fileName||"拍摄或上传健康资料"}</b><span>{fileName?status:"上传前请遮挡与解读无关的个人信息；当前单个文件上限 10MB"}</span></button><input ref={input} hidden type="file" accept="image/*,.pdf" onChange={e=>{const f=e.target.files?.[0];if(f)upload(f)}}/><div className="flow">{[["1","安全上传","文件字节保存于对象存储，元数据归属当前健康主体"],["2","质量与 OCR","服务未配置时保持等待状态，不生成结果"],["3","字段确认后解读","必须由用户确认原文、数值和单位后继续"]].map(x=><div key={x[0]}><i>{x[0]}</i><b>{x[1]}</b><span>{x[2]}</span></div>)}</div></section><section className="plain-note"><b>失败降级</b><span>格式不支持、文件过大或识别服务不可用时，不输出确定结论，并提供重传或人工路径。</span></section></div>}

function ArchivePage({member,setMember,setNotice,subjectId,bootstrap,reload}:any){const [title,setTitle]=useState("");const [familyName,setFamilyName]=useState("");const records=(bootstrap?.records??[]).filter((r:any)=>r.subjectId===subjectId);const pending=(bootstrap?.subjects??[]).filter((s:any)=>s.authorizationStatus==="pending");const add=async()=>{if(!title.trim()||!subjectId)return;try{await action({action:"create_record",subjectId,type:"note",title:title.trim(),value:{note:title.trim()},sourceType:"user_input",qualityStatus:"user_confirmed"});setTitle("");await reload();setNotice("健康记录已保存并写入审计日志")}catch{setNotice("记录未保存，请稍后重试")}};const addFamily=async()=>{if(!familyName.trim())return;try{await action({action:"create_subject",name:familyName.trim(),relation:"family"});setFamilyName("");await reload();setNotice("家庭成员已创建为待授权状态，授权完成前不会读取或写入其健康数据")}catch{setNotice("家庭成员未创建")}};return <div className="page"><PageIntro kicker="个人与家庭健康档案" title="按人、按时间，留下可追溯的健康脉络" desc="记录问答、报告、用药、设备数据、健康目标与服务记录，并清晰标注数据来源。" icon="▣"/><SubjectBar member={member} setMember={setMember} subjects={bootstrap?.subjects}/><section className="family-create"><input value={familyName} onChange={e=>setFamilyName(e.target.value)} placeholder="家庭成员姓名或称呼"/><button onClick={addFamily}>创建待授权成员</button></section>{pending.map((s:any)=><section className="pending-member" key={s.id}><div><b>{s.name}</b><span>待确认关系、管理目的和授权/监护说明</span></div><button onClick={async()=>{if(!window.confirm(`确认你有权为“${s.name}”管理健康资料，并已理解隐私与监护责任？`))return;await action({action:"authorize_subject",subjectId:s.id,confirmed:true});await reload();setNotice("家庭成员授权已记录，现在可以安全切换")}}>确认授权</button></section>)}<section className="record-create"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="手动记录一条健康动态"/><button className="primary" onClick={add}>保存记录</button></section><section className="archive-toolbar"><div><button className="selected">全部资料</button><button>问答</button><button>报告</button><button>用药</button><button>设备数据</button></div><button onClick={()=>setNotice("导出前将确认健康主体、资料范围与身份；导出生成服务待补充")}>导出档案</button></section>{records.length?<section className="record-list">{records.map((r:any)=><div key={r.id}><i>▣</i><span><b>{r.title}</b><em>{r.sourceType} · {r.qualityStatus} · {new Date(r.occurredAt).toLocaleDateString()}</em></span><button onClick={async()=>{await fetch(`/api/product?resource=record&id=${r.id}`,{method:"DELETE"});await reload();setNotice("记录已删除，关联内容需要重新计算")}}>删除</button></div>)}</section>:<section className="empty-state"><i>▣</i><h2>{member}的健康档案</h2><p>暂无健康资料。可通过上方手动记录、健康问答、资料上传或设备授权添加。</p><small>记录按健康主体隔离；AI 提取信息必须保留原始材料引用并允许更正。</small></section>}<DataSources/></div>}

function DataSources(){return <section className="source-grid">{[["用户输入","由你主动记录或确认"],["设备同步","包含设备、时间、单位与质量状态"],["医疗机构导入","保留机构与原始材料来源"],["AI 推断","明确标注，不与原始事实混淆"]].map(x=><div key={x[0]}><i/><b>{x[0]}</b><span>{x[1]}</span></div>)}</section>}

function GoalPage({setNotice,subjectId,bootstrap,reload}:any){const [type,setType]=useState("运动");const [title,setTitle]=useState("");const goals=(bootstrap?.goals??[]).filter((g:any)=>g.subjectId===subjectId);const create=async()=>{if(!subjectId||!title.trim())return;try{await action({action:"create_goal",subjectId,type,title:title.trim(),plan:{cycle:"weekly",dailyAction:"待用户编辑",checkin:"manual"},reminder:{enabled:false,time:null,frequency:"user_controlled",channel:null}});setTitle("");await reload();setNotice("目标已创建；启用提醒前仍需单独确认通知权限")}catch{setNotice("目标暂未保存")}};return <div className="page"><PageIntro kicker="健康陪伴" title="把健康目标变成可调整的日常计划" desc="目标说明、周期、行动、打卡和提醒都由你控制，可随时编辑、暂停或关闭。" icon="◎"/><section className="goal-builder"><div className="goal-types">{["运动","饮食","睡眠"].map(x=><button className={type===x?"selected":""} key={x} onClick={()=>setType(x)}>{x}</button>)}</div><input value={title} onChange={e=>setTitle(e.target.value)} placeholder={`输入${type}目标，例如“建立规律睡眠时间”`}/><button className="primary" onClick={create}>创建目标</button></section>{goals.length?<div className="goal-list">{goals.map((g:any)=><section className="plan-card" key={g.id}><div className="plan-head"><div><span>{g.status}</span><h2>{g.title}</h2><p>{g.type} · 周期、行动与提醒均可编辑</p></div><button onClick={()=>setNotice("暂停与终止状态接口将在下一次状态更新中写入")}>暂停计划</button></div><button className="primary checkin" onClick={async()=>{await action({action:"checkin",goalId:g.id});setNotice("今日打卡已记录并进入审计日志")}}>完成今日打卡</button></section>)}</div>:<section className="empty-state goal-empty"><i>◎</i><h2>还没有健康目标</h2><p>从运动、饮食或睡眠开始；系统不会生成疾病治疗、药物调整或极端计划。</p></section>}<section className="plain-note"><b>安全约束</b><span>涉及疾病治疗、药物调整或极端饮食运动的目标，会触发专业审核或就医提示。</span></section></div>}

function DevicePage({setNotice,subjectId,bootstrap,reload}:any){const device=(bootstrap?.devices??[]).find((d:any)=>d.subjectId===subjectId);const update=async(status:string)=>{try{await action({action:"device_status",subjectId,provider:"pending_provider",scopes:["activity","heart_rate","sleep"],status});await reload();setNotice(status==="pending_provider"?"授权范围已记录；仍需选择并接入真实设备平台":"设备连接状态已更新")}catch{setNotice("设备状态未保存")}};return <div className="page"><PageIntro kicker="智能设备数据接入" title="经你授权，汇总连续健康指标" desc="查看授权范围、同步状态与最近同步时间；解绑或重新授权始终由你控制。" icon="⌁"/><section className="device-card"><div className="device-icon">⌁</div><div><h2>{device?"设备接入等待服务商":"尚未连接健康设备"}</h2><p>{device?`状态：${device.status}。由于尚未配置设备平台，不会显示或推断任何健康数据。`:"连接前逐项说明活动、心率、睡眠数据的用途。品牌与指标以真实合作接口为准。"}</p></div><button className={device?"":"primary"} onClick={()=>update(device?"disconnected":"pending_provider")}>{device?"解除授权":"确认授权范围"}</button></section><div className="device-features">{[["同步状态","真实接入后显示最近同步时间与失败原因"],["数据标准化","处理单位、时区、重复记录与异常值"],["质量说明","标记缺失、延迟、异常和来源设备"],["谨慎解读","不把单次消费级设备读数当作诊断结论"]].map(x=><div key={x[0]}><i>✓</i><b>{x[0]}</b><span>{x[1]}</span></div>)}</div></div>}

function ServicePage({setNotice,subjectId}:any){const choose=async(type:string)=>{try{const result=await action({action:"service_intent",subjectId,serviceType:type,consent:{sharedFields:[],confirmed:false}});setNotice(result.externalIntegration?"正在进入服务确认":"需求已保存；尚未配置服务提供方，不会跳转、共享或收费")}catch{setNotice("服务需求未保存，请稍后重试")}};return <div className="page"><PageIntro kicker="医疗健康服务连接" title="在 AI 能力之外，连接适当的专业服务" desc="具体服务按地区、机构和账户权限展示；提供方、费用、流程与资料共享范围会在跳转前说明。" icon="✚"/><div className="service-grid">{[["◌","在线问诊","online_consultation","与真人医生进行专业咨询"],["▢","预约挂号","appointment","查询并进入可用的挂号路径"],["♙","云陪诊","cloud_companion","获取就医流程陪伴服务"]].map(x=><section key={x[1]}><i>{x[0]}</i><h2>{x[1]}</h2><p>{x[3]}</p><ul><li>确认服务提供方</li><li>确认费用与预计流程</li><li>确认资料共享范围</li></ul><button onClick={()=>choose(x[2])}>登记服务需求</button></section>)}</div><section className="confirm-band"><i>✓</i><div><b>当前不会自动跳转、共享资料或发起交易</b><span>未接入真实服务商前，只保存用户意向；后续必须再次确认提供方、费用和共享字段。</span></div></section><section className="emergency"><b>出现疑似急症？</b><span>请立即联系当地急救电话或前往急诊，不要等待在线服务。</span></section></div>}

function PrivacyModal({close,setNotice,subjectId,reload}:any){const setPermission=async(scope:string,status:string)=>{try{await action({action:"set_consent",subjectId,scope,purpose:scope==="external_ai_processing"?"将必要的健康对话发送给 DeepSeek API 生成回答":"提供对应健康功能",status});await reload?.();setNotice(status==="granted"?"授权已记录，可随时撤回":"授权已撤回，后续访问将被拒绝")}catch{setNotice("授权状态未保存")}};const deleteAccount=async()=>{if(!window.confirm("确定删除账号及全部健康数据吗？此操作无法恢复。"))return;const response=await fetch("/api/product?resource=account",{method:"DELETE"});if(response.ok){window.location.href="/signout-with-chatgpt?return_to=/"}else setNotice("账号未删除，请稍后重试")};return <div className="overlay" onClick={close}><section className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={close}>×</button><span className="modal-kicker">设置与隐私</span><h2>健康数据由你控制</h2><p>首次使用健康数据、第三方 AI、相册、麦克风或设备数据时，会分别说明用途并记录授权。</p>{[["DeepSeek 对话处理","external_ai_processing"],["健康档案","health_profile"],["相册与文件","media_processing"],["麦克风","microphone"],["设备数据","device_data"]].map(x=><div className="permission" key={x[0]}><span>{x[0]}</span><div><button onClick={()=>setPermission(x[1],"granted")}>授权</button><button onClick={()=>setPermission(x[1],"revoked")}>撤回</button></div></div>)}<div className="privacy-actions"><button onClick={()=>setNotice("数据导出生成和字段更正流程仍需补充")}>导出与更正</button><button onClick={()=>setNotice("单条记录可在健康档案中删除，并提示关联影响")}>删除数据</button><a href="/signout-with-chatgpt?return_to=/">退出登录</a></div><button className="danger wide" onClick={deleteAccount}>删除账号及全部数据</button><button className="primary wide" onClick={close}>完成</button></section></div>}

function HistoryModal({close,go,openConversation,subjectId}:any){const [q,setQ]=useState("");const [rows,setRows]=useState<any[]>([]);const search=async(value=q)=>{const response=await fetch(`/api/product?resource=history&q=${encodeURIComponent(value)}&subjectId=${encodeURIComponent(subjectId||"")}`);if(response.ok)setRows((await response.json()).conversations??[])};useEffect(()=>{search("")},[]);return <div className="overlay" onClick={close}><section className="modal history" onClick={e=>e.stopPropagation()}><button className="close" onClick={close}>×</button><span className="modal-kicker">对话记忆与检索</span><h2>查找历史健康信息</h2><label><i>⌕</i><input autoFocus value={q} onChange={e=>{setQ(e.target.value);search(e.target.value)}} placeholder="按关键词搜索"/></label><div className="filters"><button>当前健康主体</button><button>按更新时间</button><button>对话记录</button></div>{rows.length?<div className="history-list">{rows.map((r:any)=><button key={r.id} onClick={()=>openConversation(r.id)}><b>{r.title}</b><span>{r.summary||"暂无摘要"}</span><small>{new Date(r.updatedAt).toLocaleString()}</small></button>)}</div>:<div className="history-empty"><i>⌕</i><b>暂无匹配记录</b><span>完成问答后，可按关键词和健康主体检索。</span></div>}<button className="primary wide" onClick={()=>{close();go("健康问答")}}>开始新的健康问答</button></section></div>}
