import { sql } from "drizzle-orm";
import { index, integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

const timestamps = { createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`), updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`) };
export const users = sqliteTable("users", { id:text("id").primaryKey(), email:text("email").notNull(), displayName:text("display_name").notNull(), region:text("region"), status:text("status").notNull().default("active"), ...timestamps });
export const healthSubjects = sqliteTable("health_subjects", { id:text("id").primaryKey(), ownerUserId:text("owner_user_id").notNull().references(()=>users.id,{onDelete:"cascade"}), name:text("name").notNull(), relation:text("relation").notNull(), authorizationStatus:text("authorization_status").notNull().default("active"), profileJson:text("profile_json").notNull().default("{}"), ...timestamps },t=>[index("idx_health_subjects_owner").on(t.ownerUserId)]);
export const consents = sqliteTable("consents", { id:text("id").primaryKey(), ownerUserId:text("owner_user_id").notNull().references(()=>users.id,{onDelete:"cascade"}), subjectId:text("subject_id").references(()=>healthSubjects.id,{onDelete:"cascade"}), scope:text("scope").notNull(), purpose:text("purpose").notNull(), status:text("status").notNull().default("denied"), grantedAt:text("granted_at"), revokedAt:text("revoked_at"), ...timestamps },t=>[index("idx_consents_owner_scope").on(t.ownerUserId,t.scope)]);
export const conversations = sqliteTable("conversations", { id:text("id").primaryKey(), ownerUserId:text("owner_user_id").notNull().references(()=>users.id,{onDelete:"cascade"}), subjectId:text("subject_id").notNull().references(()=>healthSubjects.id,{onDelete:"cascade"}), title:text("title").notNull().default("新的健康对话"), summary:text("summary"), riskLevel:text("risk_level").notNull().default("health_management"), status:text("status").notNull().default("active"), ...timestamps },t=>[index("idx_conversations_owner_updated").on(t.ownerUserId,t.updatedAt),index("idx_conversations_subject").on(t.subjectId)]);
export const messages = sqliteTable("messages", { id:text("id").primaryKey(), conversationId:text("conversation_id").notNull().references(()=>conversations.id,{onDelete:"cascade"}), role:text("role").notNull(), content:text("content").notNull(), inputType:text("input_type").notNull().default("text"), sourcesJson:text("sources_json").notNull().default("[]"), contextJson:text("context_json").notNull().default("{}"), riskLevel:text("risk_level").notNull().default("health_management"), modelVersion:text("model_version"), createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) },t=>[index("idx_messages_conversation_created").on(t.conversationId,t.createdAt)]);
export const feedback = sqliteTable("feedback", { id:text("id").primaryKey(), ownerUserId:text("owner_user_id").notNull().references(()=>users.id,{onDelete:"cascade"}), messageId:text("message_id").notNull().references(()=>messages.id,{onDelete:"cascade"}), type:text("type").notNull(), details:text("details"), createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) },t=>[index("idx_feedback_message").on(t.messageId)]);
export const healthRecords = sqliteTable("health_records", { id:text("id").primaryKey(), ownerUserId:text("owner_user_id").notNull().references(()=>users.id,{onDelete:"cascade"}), subjectId:text("subject_id").notNull().references(()=>healthSubjects.id,{onDelete:"cascade"}), type:text("type").notNull(), title:text("title").notNull(), valueJson:text("value_json").notNull().default("{}"), sourceType:text("source_type").notNull(), sourceRef:text("source_ref"), qualityStatus:text("quality_status").notNull().default("unverified"), occurredAt:text("occurred_at").notNull(), ...timestamps },t=>[index("idx_records_owner_subject_time").on(t.ownerUserId,t.subjectId,t.occurredAt),index("idx_records_subject_type").on(t.subjectId,t.type)]);
export const uploads = sqliteTable("uploads", { id:text("id").primaryKey(), ownerUserId:text("owner_user_id").notNull().references(()=>users.id,{onDelete:"cascade"}), subjectId:text("subject_id").notNull().references(()=>healthSubjects.id,{onDelete:"cascade"}), objectKey:text("object_key").notNull(), fileName:text("file_name").notNull(), contentType:text("content_type").notNull(), size:integer("size").notNull(), status:text("status").notNull().default("uploaded"), qualityJson:text("quality_json").notNull().default("{}"), createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) },t=>[index("idx_uploads_owner_created").on(t.ownerUserId,t.createdAt)]);
export const goals = sqliteTable("goals", { id:text("id").primaryKey(), ownerUserId:text("owner_user_id").notNull().references(()=>users.id,{onDelete:"cascade"}), subjectId:text("subject_id").notNull().references(()=>healthSubjects.id,{onDelete:"cascade"}), type:text("type").notNull(), title:text("title").notNull(), planJson:text("plan_json").notNull().default("{}"), reminderJson:text("reminder_json").notNull().default("{}"), status:text("status").notNull().default("active"), ...timestamps },t=>[index("idx_goals_owner_subject_status").on(t.ownerUserId,t.subjectId,t.status)]);
export const goalCheckins = sqliteTable("goal_checkins", { id:text("id").primaryKey(), goalId:text("goal_id").notNull().references(()=>goals.id,{onDelete:"cascade"}), ownerUserId:text("owner_user_id").notNull().references(()=>users.id,{onDelete:"cascade"}), status:text("status").notNull().default("completed"), note:text("note"), createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) },t=>[index("idx_checkins_goal_created").on(t.goalId,t.createdAt)]);
export const deviceConnections = sqliteTable("device_connections", { id:text("id").primaryKey(), ownerUserId:text("owner_user_id").notNull().references(()=>users.id,{onDelete:"cascade"}), subjectId:text("subject_id").notNull().references(()=>healthSubjects.id,{onDelete:"cascade"}), provider:text("provider").notNull(), scopesJson:text("scopes_json").notNull().default("[]"), status:text("status").notNull().default("disconnected"), lastSyncedAt:text("last_synced_at"), ...timestamps },t=>[index("idx_devices_owner_subject").on(t.ownerUserId,t.subjectId)]);
export const serviceEvents = sqliteTable("service_events", { id:text("id").primaryKey(), ownerUserId:text("owner_user_id").notNull().references(()=>users.id,{onDelete:"cascade"}), subjectId:text("subject_id").notNull().references(()=>healthSubjects.id,{onDelete:"cascade"}), serviceType:text("service_type").notNull(), provider:text("provider"), status:text("status").notNull().default("draft"), consentJson:text("consent_json").notNull().default("{}"), createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`), updatedAt:text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`) },t=>[index("idx_services_owner_created").on(t.ownerUserId,t.createdAt)]);
export const auditEvents = sqliteTable("audit_events", { id:text("id").primaryKey(), ownerUserId:text("owner_user_id").notNull(), subjectId:text("subject_id"), action:text("action").notNull(), resourceType:text("resource_type").notNull(), resourceId:text("resource_id"), metadataJson:text("metadata_json").notNull().default("{}"), modelVersion:text("model_version"), createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) },t=>[index("idx_audit_owner_created").on(t.ownerUserId,t.createdAt),index("idx_audit_resource").on(t.resourceType,t.resourceId)]);
